language: java
before_script:
  - if test -z "$LOCALCLASSPATH"; then export LOCALCLASSPATH="/usr/share/java/xmlParserAPIs.jar:/usr/share/java/xercesImpl.jar"; else export LOCALCLASSPATH="/usr/share/java/xmlParserAPIs.jar:/usr/share/java/xercesImpl.jar:$LOCALCLASSPATH"; fi
script:
  - ./build.sh
